# Generated by Django 5.1.3 on 2024-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletins", "0003_alter_bulletin_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="hashtags",
            field=models.TextField(
                blank=True, default="", help_text="Введите хэштеги через запятую"
            ),
        ),
    ]
